import React, { useContext, useEffect, useReducer, useState } from "react";

import Head from "next/head";

import { TodosContext } from "@/state";
import { todosReducer } from "@/state/reducers";
import TodoList from "@/components/todoList";
import Navbar from "@/components/navbar";
import { todoList } from "@/mocks/todoList";

import { db } from "../plugins/firebase";
import { collection, getDocs } from "firebase/firestore";

import styles from "@/styles/Home.module.scss";

export default function Home({ data }) {
  // const { state, dispatch } = useContext(TodosContext);
  const [state, dispatch] = useReducer(todosReducer, { data: todoList });

  return (
    <>
      <Head>
        <title> Todo List </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodosContext.Provider value={{ state: { data }, dispatch }}>
        <main className={styles.Main}>
          <Navbar />
          <TodoList />
        </main>
      </TodosContext.Provider>
    </>
  );
}

export async function getServerSideProps() {
  const data = [];
  const querySnapshot = await getDocs(collection(db, "todos-list"));
  querySnapshot.forEach((doc) => {
    data.push(doc.data());
  });
  return {
    props: {
      data,
    },
  };
}
