import React from "react";

import Head from "next/head";

import styles from "../styles/Login.module.scss";

export default function Login() {
  const onHandleClick = () => {
    console.log("Cazzo");
  };
  return (
    <>
      <Head>
        <title> Login </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.Login}>
        <h1>Welcome!</h1>
        <p>Please, log-in to save your tasks!</p>

        <button className={styles.Login__Button} onClick={onHandleClick}>
          Log-in with Google
        </button>
      </main>
    </>
  );
}
